name: Build Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: rustconxyz
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build Docker Image
        run: |
          docker build . --tag ghcr.io/rustconxyz/api:latest
          docker push ghcr.io/rustconxyz/api:latest
